// Inline color-markup concealment: findColorTagPairs must match exactly
// the plugin's own tag shapes, pair them correctly (including nesting),
// and carry the style to re-apply on the inner text.
import { findColorTagPairs } from "./bundle.mjs";

let fail = 0;
const ok = (name, cond, extra = "") => {
  if (!cond) fail++;
  console.log(`${cond ? "PASS" : "FAIL"} ${name}${cond ? "" : " :: " + extra}`);
};

// Simple color span.
{
  const text = 'before <span style="color:var(--color-red)">red text</span> after';
  const p = findColorTagPairs(text);
  ok("span pair found", p.length === 1, JSON.stringify(p));
  ok("span style captured", p[0].style === "color:var(--color-red)", p[0].style);
  ok(
    "span inner range",
    text.slice(p[0].open.to, p[0].close.from) === "red text",
    text.slice(p[0].open.to, p[0].close.from)
  );
}

// Highlight mark.
{
  const text = '<mark style="background:rgba(var(--color-yellow-rgb),0.20);color:inherit">hi</mark>';
  const p = findColorTagPairs(text);
  ok("mark pair found", p.length === 1, JSON.stringify(p));
  ok(
    "mark style captured",
    p[0].style === "background:rgba(var(--color-yellow-rgb),0.20)",
    p[0].style
  );
}

// Underline HTML generated by the toolbar.
{
  const text = "before <u>underlined</u> after";
  const p = findColorTagPairs(text);
  ok("underline pair found", p.length === 1, JSON.stringify(p));
  ok(
    "underline style captured",
    p[0].style === "text-decoration:underline",
    p[0].style
  );
  ok(
    "underline inner range",
    text.slice(p[0].open.to, p[0].close.from) === "underlined",
    text.slice(p[0].open.to, p[0].close.from)
  );
}

// Table cell / table markers (class-only, no inner style).
{
  const text = '| <span class="nf-tbl-blue"></span>Head | <span class="nf-cell-red">cell</span> |';
  const p = findColorTagPairs(text);
  ok("cell + tbl markers found", p.length === 2, JSON.stringify(p));
  ok("markers carry no style", p.every((x) => x.style === null));
}

// Nested mark inside span pairs up correctly.
{
  const text = '<span style="color:red">a <mark style="background:blue;color:inherit">b</mark> c</span>';
  const p = findColorTagPairs(text);
  ok("nested pairs found", p.length === 2, JSON.stringify(p));
  const span = p.find((x) => x.style === "color:red");
  const mark = p.find((x) => x.style === "background:blue");
  ok("nested: mark sits inside span", mark.open.from > span.open.to && mark.close.to < span.close.from);
}

// Underline and color tags remain properly nested in either order, which is
// required when both conceal decorations overlap the same selected text.
for (const text of [
  '<u><span style="color:red">word</span></u>',
  '<span style="color:red"><u>word</u></span>',
]) {
  const p = findColorTagPairs(text);
  const underline = p.find((x) => x.style === "text-decoration:underline");
  const color = p.find((x) => x.style === "color:red");
  ok("nested underline + color pairs found", p.length === 2 && !!underline && !!color, JSON.stringify(p));
  if (underline && color) {
    const underlineContainsColor =
      underline.open.to <= color.open.from && color.close.to <= underline.close.from;
    const colorContainsUnderline =
      color.open.to <= underline.open.from && underline.close.to <= color.close.from;
    ok("nested underline + color containment", underlineContainsColor || colorContainsUnderline, JSON.stringify(p));
  }
}

// Unmatched tags and foreign HTML are left alone.
{
  ok("lone close ignored", findColorTagPairs("text </span> more").length === 0);
  ok("lone open ignored", findColorTagPairs('<span style="color:red">no close').length === 0);
  ok(
    "foreign span not matched",
    findColorTagPairs('<span class="other">x</span>').length === 0
  );
  ok(
    "url-smuggling style not matched",
    findColorTagPairs('<span style="color:red;background:url(//x)">x</span>').length === 0
  );
}

process.exit(fail ? 1 : 0);
