// Generates the note-style palette tokens (+ contrast report) from palettes.mjs and keeps the
// generated block in styles.css — between the two marker comments START / END below — in sync.
//
//   npm run gen:styles                     regenerate the block in styles.css (only between the markers)
//   npm run gen:styles -- --check          compare only: exit 0 when up to date, 1 when it differs
//   node scripts/style-presets/gen.mjs --stdout            print the block body (no markers/header), touch nothing
//   node scripts/style-presets/gen.mjs --css <path>        target another stylesheet (a scratch copy)
//   node scripts/style-presets/gen.mjs --json <path>       also write tokens.json there (for designers)
//   node scripts/style-presets/gen.mjs --report <path>     also write the contrast summary there
// (Flags need the `--` separator when passed through `npm run`.)
//
// Every ink is nudged in OKLCH lightness until its contrast pairs pass; if any hard check still fails,
// the script prints the failures and exits 1 BEFORE writing anything. Exit 2 = usage or marker error
// (0 or several START/END markers, or END before START). The contrast summary always goes to stderr.
// Importing this module has no side effects (the unit test imports generate()).
import fs from 'node:fs';
import { fileURLToPath } from 'node:url';
import { hex2rgb, rgb2hex, contrast, ok, rgb2oklch, over, solveTint, mixOklab } from './color.mjs';
import { PALETTES, HUES, BG, OBS_RAMP, curTintHex } from './palettes.mjs';

export const START = '/* @generated note-style tokens:start */';
export const END = '/* @generated note-style tokens:end */';
export const HEADER = '/* Generated by `npm run gen:styles` (scripts/style-presets/gen.mjs) from scripts/style-presets/palettes.mjs. Edit palettes.mjs, not this block. */';

const ALPHA = h => (h === 'yellow' ? 0.2 : 0.18);
// Callout fills under a palette (share of the wash source over the page), per look.
export const CO_FILL = { light: { box: 0.14, card: 0.16, rail: 0.10, strip: 0.35 }, dark: { box: 0.10, card: 0.12, rail: 0.08, strip: 0.35 } };
// Table / cell washes (light keeps today's alphas; dark is tokenised lower under a palette)
// Gradient look: body fill + title-strip peak (share of the wash source); see layer F1 --nf-co-grad
export const GRAD = { light: { fill: 0.07, peak: 0.26 }, dark: { fill: 0.06, peak: 0.22 }, titleInk: 0.70 };
const CELL_A = { light: h => (h === 'yellow' ? 0.28 : 0.25), dark: () => 0.20 };
const THEAD_A = { light: 0.22, dark: 0.16 };

const toRgb = x => (typeof x === 'string' ? hex2rgb(x) : x);
const parseRgba = (s, bg) => {
  if (s.startsWith('#')) return hex2rgb(s);
  const [r, g, b, a] = s.match(/[\d.]+/g).map(Number);
  return over([r, g, b], a, toRgb(bg)).map(Math.round);
};
const hexOf = x => (typeof x === 'string' ? x : rgb2hex(x));
const fromLch = a => rgb2hex(ok(...a));
const lchOf = hex => rgb2oklch(hex2rgb(hex));
/** move a colour's OKLCH lightness (dir -1 darker / +1 lighter) until pred passes */
function nudge(hex, dir, pred, maxSteps = 60) {
  let [L, C, H] = lchOf(hex), out = hex, n = 0;
  while (!pred(out) && n < maxSteps) { L += dir * 0.005; out = rgb2hex(ok(L, C, H)); n++; }
  return { hex: out, steps: n };
}
function deriveRamp(paper, text, mode) {
  const ref = OBS_RAMP[mode];
  const L0 = lchOf(ref['00'])[0], L1 = lchOf(ref['100'])[0];
  const p = lchOf(paper), t = lchOf(text);
  const out = {};
  for (const [k, v] of Object.entries(ref)) {
    const f = (lchOf(v)[0] - L0) / (L1 - L0);
    // interpolate L linearly, keep a little of the paper's chroma/hue
    const L = p[0] + (t[0] - p[0]) * f;
    const C = p[1] * (1 - f) + t[1] * f;
    const H = f < 0.5 ? p[2] : t[2];
    out[k] = rgb2hex(ok(L, C, H));
  }
  out['00'] = paper; out['100'] = text;
  return out;
}

const RAMP_KEYS = ['00', '05', '10', '20', '25', '30', '35', '40', '50', '60', '70', '100'];
const block = (sel, m) => {
  const L = [];
  for (const h of HUES) L.push(`  --nf-${h}: ${m.ink[h]};`, `  --nf-${h}-rgb: ${m.washSrc[h]};`);
  L.push(`  --nf-style-text: ${m.text};`, `  --nf-style-heading: ${m.heading};`, `  --nf-style-heading-tint: ${m.headingTint};`,
    `  --nf-style-muted: ${m.muted};`, `  --nf-style-link: ${m.link};`, `  --nf-style-decor: ${m.decor};`, `  --nf-style-decor-ink: ${m.decorInk};`,
    `  --nf-style-list-marker: ${m.listMarker};`, `  --nf-style-quote-bar: ${m.quoteBar};`, `  --nf-style-quote-width: ${m.quoteWidth};`,
    `  --nf-style-inline-code: ${m.inlineCode};`, `  --nf-style-inline-code-bg: ${m.inlineCodeBg};`,
    `  --nf-style-thead: ${m.thead};`, `  --nf-style-stripe: ${m.stripe};`, `  --nf-style-hr: ${m.hr};`, `  --nf-style-border: ${m.border};`,
    `  --nf-style-rule: ${m.muted};`, `  --nf-style-paper: ${m.paper};`);
  for (const k of RAMP_KEYS) L.push(`  --nf-style-base-${k}: ${m.ramp[k]};`);
  for (const [k, v] of Object.entries(m.code)) L.push(`  --nf-style-code-${k}: ${v};`);
  return `${sel} {\n${L.join('\n')}\n}\n`;
};

/** Build every palette's tokens and run the contrast checks. Pure: writes nothing.
 *  → { out: tokens.json object, css: the token block body, report, fails, adjust, summary: contrast.txt text } */
export function generate() {
  const report = [], fails = [], adjust = [];
  const check = (label, v, min, where) => { report.push({ label, v: +v.toFixed(2), min, where }); if (v < min - 1e-9) fails.push(`${where}: ${label} ${v.toFixed(2)} < ${min}`); };

  const out = {};
  for (const P of PALETTES) {
    out[P.id] = { id: P.id, nameEn: P.nameEn, nameZh: P.nameZh, descEn: P.descEn, descZh: P.descZh, group: P.group, look: P.look, canvas: P.canvas, inkHues: P.inkHues };
    for (const mode of ['light', 'dark']) {
      let S = P[mode]; const dir = mode === 'light' ? -1 : 1, bgHex = BG[mode], bg = hex2rgb(bgHex);
      const where = `${P.id}/${mode}`;
      // ---- wash sources
      let washSrc = S.washSrc;
      if (!washSrc) {
        washSrc = {};
        const tints = curTintHex(P.washTint, mode);
        const baseC = P.washC[mode];
        for (const h of HUES) {
          const H = lchOf(tints[h])[2];
          let L = mode === 'light' ? 0.952 : 0.305, C = baseC;
          if (h === 'yellow') { L = mode === 'light' ? 0.968 : 0.325; C = baseC * (mode === 'light' ? 1.9 : 1.15); }
          if (h === 'gray') C = baseC * (mode === 'light' ? 0.35 : 0.3);
          if (h === 'orange' && mode === 'light') L = 0.955;
          washSrc[h] = solveTint(ok(L, C, H), ALPHA(h), bg);
        }
      }
      const wash = Object.fromEntries(HUES.map(h => [h, rgb2hex(over(washSrc[h], ALPHA(h), bg))]));
      // ---- ramp / paper
      const ramp = S.ramp ? { ...S.ramp } : deriveRamp(S.paper, S.text, mode);
      const paper = S.ramp ? S.ramp['00'] : S.paper;
      const surfaces = [bgHex, paper];
      const surfaceNames = ['theme', 'paper'];
      // ---- inks (ensure on every surface, on own wash, on callout strips)
      const ink = { ...S.ink };
      const coBg = (h, surf, pct) => rgb2hex(over(washSrc[h], pct, hex2rgb(surf)));
      const F = CO_FILL[mode];
      const stripOn = (h, surf) => { const body = over(washSrc[h], F.box, hex2rgb(surf)); return rgb2hex(over(washSrc[h], F.box * F.strip, body)); };
      const gradOn = (h, surf) => { const G = GRAD[mode]; const body = over(washSrc[h], G.fill, hex2rgb(surf)); return rgb2hex(over(washSrc[h], G.peak, body)); };
      for (const h of HUES) {
        const pred = x => surfaces.every(s => contrast(x, s) >= 4.52)
          && surfaces.every(s => contrast(x, rgb2hex(over(washSrc[h], ALPHA(h), hex2rgb(s)))) >= 4.52)
          && surfaces.every(s => contrast(x, stripOn(h, s)) >= 4.52 && contrast(x, coBg(h, s, F.card)) >= 4.52);
        const r = nudge(ink[h], dir, pred);
        if (r.steps) adjust.push(`${where} ink.${h} ${ink[h]} → ${r.hex} (${r.steps} steps)`);
        ink[h] = r.hex;
      }
      // body text / heading ≥ 7:1 (AAA) and muted ≥ 4.6:1 on both surfaces — nudge lightness only
      const T = {};
      for (const [k, min] of [['text', 7.05], ['heading', 7.05], ['muted', 4.6]]) {
        const r = nudge(S[k], dir, x => surfaces.every(s => contrast(x, s) >= min));
        if (r.steps) adjust.push(`${where} ${k} ${S[k]} → ${r.hex}`);
        T[k] = r.hex;
      }
      S = { ...S, ...T }; ramp['100'] = S.text;
      const resolveHue = v => (HUES.includes(v) ? ink[v] : v);
      const inlineCodeHex = resolveHue(S.inlineCode);
      const pill = hexOf(parseRgba(S.inlineCodeBg, bg));
      const link = S.link === 'blue' ? ink.blue : S.link;
      const headingTint = Array.isArray(S.headingTint) ? fromLch(S.headingTint) : S.headingTint;
      // non-text UI colours ≥ 3:1 on both surfaces
      const ui = {};
      for (const k of ['listMarker', 'quoteBar', 'decor']) {
        const r = nudge(S[k], dir, x => surfaces.every(s => contrast(x, s) >= 3.05));
        if (r.steps) adjust.push(`${where} ${k} ${S[k]} → ${r.hex}`);
        ui[k] = r.hex;
      }
      const decorInk = nudge(ui.decor, dir, x => surfaces.every(s => contrast(x, s) >= 4.6)).hex;
      // code tokens ≥ 4.5 on the code card
      const code = { ...S.code };
      for (const [k, v] of Object.entries(code)) {
        if (k === 'bg') continue;
        const r = nudge(v, dir, x => contrast(x, code.bg) >= 4.55);
        if (r.steps) adjust.push(`${where} code.${k} ${v} → ${r.hex}`);
        code[k] = r.hex;
      }
      // ---- checks
      for (const [i, s] of surfaces.entries()) {
        const sw = `${where}/${surfaceNames[i]}`;
        check('text on page', contrast(S.text, s), 7, sw);
        check('heading on page', contrast(S.heading, s), 7, sw);
        check('muted on page', contrast(S.muted, s), 4.5, sw);
        check('link on page', contrast(link, s), 4.5, sw);
        check('tinted heading on page', contrast(headingTint, s), 7, sw);
        check('decor ink on page', contrast(decorInk, s), 4.5, sw);
        for (const k of ['listMarker', 'quoteBar', 'decor']) check(`${k} on page (UI)`, contrast(ui[k], s), 3, sw);
        for (const h of HUES) {
          check('ink on page', contrast(ink[h], s), 4.5, `${sw}/${h}`);
          check('callout title ink on header strip', contrast(ink[h], stripOn(h, s)), 4.5, `${sw}/${h}`);
          check('callout title ink on card fill', contrast(ink[h], coBg(h, s, F.card)), 4.5, `${sw}/${h}`);
          check('gradient title (70% ink in oklab) on strip peak', contrast(mixOklab(ink[h], GRAD.titleInk, S.text), gradOn(h, s)), 4.5, `${sw}/${h}`);
          check('body text on callout rail/outline fill', contrast(S.text, coBg(h, s, F.rail)), 4.5, `${sw}/${h}`);
          check('body text on callout card fill', contrast(S.text, coBg(h, s, F.card)), 4.5, `${sw}/${h}`);
          check('body text on highlight', contrast(S.text, rgb2hex(over(washSrc[h], ALPHA(h), hex2rgb(s)))), 4.5, `${sw}/${h}`);
          check('body text on cell wash', contrast(S.text, rgb2hex(over(washSrc[h], CELL_A[mode](h), hex2rgb(s)))), 4.5, `${sw}/${h}`);
          check('body text on tinted table header', contrast(S.text, rgb2hex(over(washSrc[h], THEAD_A[mode], hex2rgb(s)))), 4.5, `${sw}/${h}`);
        }
      }
      for (const h of HUES) for (const [i, s] of surfaces.entries()) check('ink on its own highlight', contrast(ink[h], rgb2hex(over(washSrc[h], ALPHA(h), hex2rgb(s)))), 4.5, `${where}/${surfaceNames[i]}/${h}`);
      check('text on table header', contrast(S.text, hexOf(parseRgba(S.thead, bg))), 4.5, where);
      check('inline code on pill', contrast(inlineCodeHex, pill), 4.5, where);
      for (const [k, v] of Object.entries(code)) if (k !== 'bg') check('code token on code bg', contrast(v, code.bg), 4.5, `${where}/${k}`);
      out[P.id][mode] = {
        ink, washSrc: Object.fromEntries(HUES.map(h => [h, washSrc[h].join(', ')])), wash,
        text: S.text, heading: S.heading, headingTint, muted: S.muted, link, decor: ui.decor, decorInk,
        listMarker: ui.listMarker, quoteBar: ui.quoteBar, quoteWidth: S.quoteWidth,
        inlineCode: HUES.includes(S.inlineCode) ? `var(--nf-${S.inlineCode})` : S.inlineCode, inlineCodeHex, inlineCodeBg: S.inlineCodeBg,
        thead: S.thead, stripe: S.stripe, hr: S.hr, border: S.border, paper, ramp, code,
      };
    }
  }

  // ---------- CSS ----------
  let css = '';
  for (const [id, p] of Object.entries(out)) {
    css += `/* ---------- ${p.nameEn} · ${p.nameZh} — ${p.descEn} ---------- */\n`;
    css += block(`body.nf-palette-${id},\n.nf-palette-preview[data-palette="${id}"]`, p.light);
    css += block(`body.theme-dark.nf-palette-${id},\n.theme-dark .nf-palette-preview[data-palette="${id}"]`, p.dark);
    css += '\n';
  }
  // contrast summary: minimum per label
  const agg = {};
  for (const r of report) { if (!agg[r.label] || r.v < agg[r.label].v) agg[r.label] = r; }
  let summary = 'MINIMUM PER CHECK (all palettes × light/dark × {theme bg, paper tone})\n';
  for (const [k, r] of Object.entries(agg)) summary += `${(r.v >= r.min ? 'ok  ' : 'FAIL')} ${k.padEnd(40)} min ${String(r.v).padEnd(6)} (need ${r.min})  @ ${r.where}\n`;
  summary += `\nPairs checked: ${report.length}\nAdjustments made by the ensure pass (OKLCH lightness only):\n` + (adjust.length ? adjust.map(a => '  ' + a).join('\n') : '  none') + '\n';
  summary += `\nFailures: ${fails.length}\n` + fails.map(f => '  ' + f).join('\n') + '\n';
  return { out, css, report, fails, adjust, summary };
}

/* ---------- the block in styles.css ---------- */

/** The block as it sits between the markers: header comment + the generated CSS. */
export const renderBody = css => HEADER + '\n' + css.trimEnd();

/** Split a stylesheet at the markers → { before, body, after }, where body is strictly between
 *  the end of START and the start of END. Throws { code: 'MARKERS' } unless there is exactly
 *  one START and one END, START first. */
export function extractBlock(text) {
  const count = m => text.split(m).length - 1;
  const starts = count(START), ends = count(END);
  const fail = msg => Object.assign(new Error(msg), { code: 'MARKERS' });
  if (starts === 0 && ends === 0) throw fail('markers not found');
  if (starts !== 1 || ends !== 1) throw fail(`expected exactly one start and one end marker, found ${starts} start and ${ends} end`);
  const s = text.indexOf(START), e = text.indexOf(END);
  if (e < s) throw fail('end marker comes before the start marker');
  return { before: text.slice(0, s + START.length), body: text.slice(s + START.length, e), after: text.slice(e) };
}

/** Comparable form of a block body: LF line ends, no generator header line, trimmed. A verbatim
 *  paste of the generated CSS (without HEADER) compares equal to a regenerated block. */
export function normalizeBody(body) {
  let t = body.replace(/\r\n/g, '\n').trim();
  if (t.startsWith('/* Generated by `npm run gen:styles`')) {
    const nl = t.indexOf('\n');
    t = nl < 0 ? '' : t.slice(nl + 1);
  }
  return t.trim();
}

/** The stylesheet with the block replaced; the markers and everything outside them stay
 *  byte-identical, with exactly one newline after START and one before END. */
export function replaceBlock(text, css) {
  const { before, after } = extractBlock(text);
  return before + '\n' + renderBody(css) + '\n' + after;
}

/* ---------- CLI (only when run directly) ---------- */

function main(argv) {
  const opts = { check: false, stdout: false, css: null, json: null, report: null };
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (a === '--check') opts.check = true;
    else if (a === '--stdout') opts.stdout = true;
    else if (a === '--css' || a === '--json' || a === '--report') {
      const v = argv[++i];
      if (!v || v.startsWith('--')) { console.error(`gen:styles: ${a} needs a path`); return 2; }
      opts[a.slice(2)] = v;
    } else { console.error(`gen:styles: unknown argument ${a}\nusage: gen.mjs [--check] [--stdout] [--css <path>] [--json <path>] [--report <path>]`); return 2; }
  }
  const { out, css, fails, summary } = generate();
  process.stderr.write(summary);
  if (fails.length) {
    console.error(`gen:styles: ${fails.length} contrast failure(s); nothing was written:\n` + fails.map(f => '  ' + f).join('\n'));
    return 1;
  }
  if (opts.json) fs.writeFileSync(opts.json, JSON.stringify(out, null, 1));
  if (opts.report) fs.writeFileSync(opts.report, summary);
  if (opts.stdout) { process.stdout.write(css); return 0; }
  const target = opts.css ?? fileURLToPath(new URL('../../styles.css', import.meta.url));
  const name = opts.css ?? 'styles.css';
  let text;
  try { text = fs.readFileSync(target, 'utf8'); }
  catch (error) { console.error(`gen:styles: cannot read ${target} (${error.message})`); return 2; }
  let current;
  try { current = extractBlock(text); }
  catch (error) {
    if (error.code !== 'MARKERS') throw error;
    console.error(`gen:styles: ${error.message === 'markers not found' ? `markers not found in ${name}` : `${error.message} in ${name}`} (${START} … ${END})`);
    return 2;
  }
  if (opts.check) {
    if (normalizeBody(current.body) === normalizeBody(css)) { console.error(`gen:styles: ${name} is up to date`); return 0; }
    const a = normalizeBody(current.body).split('\n'), b = normalizeBody(css).split('\n');
    let i = 0;
    while (i < a.length && i < b.length && a[i] === b[i]) i++;
    console.error(`gen:styles: the token block in ${name} differs from palettes.mjs (first at block line ${i + 1}: ${JSON.stringify(a[i] ?? '<end>')} vs ${JSON.stringify(b[i] ?? '<end>')}); run npm run gen:styles`);
    return 1;
  }
  const next = replaceBlock(text, css);
  if (next === text) { console.error(`gen:styles: ${name} is up to date`); return 0; }
  fs.writeFileSync(target, next);
  console.error(`gen:styles: updated the token block in ${name}`);
  return 0;
}

// realpath on both sides: /tmp → /private/tmp style symlinks would otherwise defeat the comparison.
const isMain = (() => {
  try { return !!process.argv[1] && fs.realpathSync(process.argv[1]) === fs.realpathSync(fileURLToPath(import.meta.url)); }
  catch { return false; }
})();
if (isMain) process.exitCode = main(process.argv.slice(2));
